// Central lookup so skill/value icon names stored as plain strings (in the
// database or data file) can be rendered with the matching Lucide icon.
import {
  FileCode,
  Palette,
  Braces,
  Atom,
  Smartphone,
  Terminal,
  Server,
  Plug,
  Hexagon,
  Database,
  DatabaseZap,
  Leaf,
  Table,
  Wrench,
  Printer,
  Network,
  Waypoints,
  Monitor,
  Cpu,
  GitBranch,
  Github,
  Code,
  Layers,
  Box,
  Boxes,
  Sparkles,
  Webhook,
  SquareTerminal,
  Cloud,
  BrainCircuit,
  BookOpen,
  Puzzle,
  Lightbulb,
  Rocket,
  Target,
  Code2,
} from "lucide-react";

const ICON_MAP = {
  "file-code": FileCode,
  palette: Palette,
  braces: Braces,
  atom: Atom,
  smartphone: Smartphone,
  terminal: Terminal,
  server: Server,
  plug: Plug,
  hexagon: Hexagon,
  database: Database,
  "database-zap": DatabaseZap,
  leaf: Leaf,
  table: Table,
  wrench: Wrench,
  printer: Printer,
  network: Network,
  waypoints: Waypoints,
  monitor: Monitor,
  cpu: Cpu,
  "git-branch": GitBranch,
  github: Github,
  code: Code,
  layers: Layers,
  box: Box,
  boxes: Boxes,
  sparkles: Sparkles,
  webhook: Webhook,
  "square-terminal": SquareTerminal,
  cloud: Cloud,
  "brain-circuit": BrainCircuit,
  "book-open": BookOpen,
  puzzle: Puzzle,
  lightbulb: Lightbulb,
  rocket: Rocket,
  target: Target,
};

export function getIcon(name) {
  return ICON_MAP[name] || Code2;
}
