# Generated by Django 5.0.7 on 2026-07-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('issue_date', models.CharField(help_text="e.g. '2024' or 'March 2024'", max_length=50)),
                ('credential_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=150)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('start_date', models.CharField(help_text="e.g. '2024' or 'Jan 2024'", max_length=50)),
                ('end_date', models.CharField(blank=True, help_text='Leave blank if this is ongoing.', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True, help_text='One responsibility per line.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(help_text='Short summary shown on the project card.')),
                ('detailed_description', models.TextField(blank=True, help_text='Longer write-up shown in the project details modal/page.')),
                ('problem', models.TextField(blank=True, help_text='What problem the project addresses.')),
                ('solution', models.TextField(blank=True, help_text='How the project solves that problem.')),
                ('role', models.CharField(blank=True, help_text='My role on the project.', max_length=200)),
                ('lessons_learned', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('web', 'Web Development'), ('software', 'Software Systems'), ('mobile', 'Mobile'), ('business', 'Business'), ('entrepreneurship', 'Entrepreneurship')], default='web', max_length=20)),
                ('technologies', models.CharField(help_text="Comma-separated list, e.g. 'Python, Django, SQLite'", max_length=300)),
                ('features', models.TextField(blank=True, help_text='One feature per line.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('frontend', 'Frontend Development'), ('backend', 'Backend Development'), ('database', 'Database'), ('it_support', 'IT Support & Networking'), ('tools', 'Tools'), ('learning', 'Currently Learning')], max_length=20)),
                ('proficiency', models.PositiveIntegerField(default=50, help_text='Honest skill level from 0-100.')),
                ('icon', models.CharField(blank=True, help_text="Lucide icon name, e.g. 'code', 'database'.", max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
