# Generated by Django 6.0.7 on 2026-08-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of the certificate.'),
        ),
    ]
